name: pyrnotebook3
channels:
  - conda-forge
  - conda 
  - pytorch
  - pypi
dependencies:
  - r-essentials
  - r-tensorflow
  - r-keras
  - r-boot
  - r-caret
  - r-learnr
  - r-rstan
  - r-brms
  - r-mlr
  - r-superlearner
  - r-cairo
  - r-forecast
  - r-autoshiny
  - r-acepack
  - r-rjava
  - r-leaps
  - r-regnet
  - r-aspect
  - r-sem 
  - r-polycor
  - r-ggvis
  - r-relimp
  - r-sparklyr
  - r-sparkr
  - r-sparsemvn
  - r-sparsesem
  - r-sparsesvd
  - r-sparsesvm
  - r-clustergeneration
  - r-sautomata
  - r-arules
  - r-arulescba
  - r-arulessequences
  - r-cloudml
  - r-dbplyr
  - r-domino
  - r-fastrweb
  - r-h2o
  - r-leaps
  - r-onnx
  - r-plumber
  - r-pmml
  - r-pmmltransformations
  - r-rserve
  - r-sparklyr
  - r-sparkr
  - r-tidytext
  - r-tidyselect
  - r-tidyverse
  - r-tilting
  - r-xgboost
  - r-bnlearn
  - r-bnclassify
  - r-bnn
  - r-boolnet
  - r-ggm
  - r-ggmridge
  - r-ggmselect
  - r-xgobi
  - r-xml
  - r-mgcv
  - r-yhatr
  - r-bart
  - r-biglm
  - r-biglmm
  - r-bigmap
  - r-bigml
  - r-biganalytics
  - r-bigalgebra
  - r-bigintegeralgos
  - r-bigreadr
  - r-bigreg
  - r-bigsplines
  - r-bigtabulate
  - r-bigtime
  - r-bigvar
  - r-boruta
  - r-corelearn
  - r-deepnet
  - r-elasticnet
  - r-ggm
  - r-gglasso
  - r-ggplot2movies
  - r-ggmselect
  - r-ggmridge
  - r-gfa
  - r-gmmboost
  - r-gbm
  - r-gb
  - r-gcdnet
  - r-gcd
  - r-glmpath
  - r-gamboost
  - r-gmmboost
  - r-jousboost
  - r-l2boost
  - r-clogitboost
  - r-compboost
  - r-deepboost
  - r-fastadaboost
  - r-aucrf
  - r-partitionmap
  - r-rfinterval
  - r-rlt
  - r-softrandomforest
  - r-spatialml
  - r-varselrf
  - r-blockforest
  - r-imputemissings
  - r-multivariaterandomforest
  - r-rfutilities
  - r-auc
  - r-eive
  - r-frbs
  - r-gaselect
  - r-genalg
  - r-glmulti
  - r-kofnga
  - r-rgenoud
  - r-g3viz
  - r-gadag
  - r-gafit
  - r-feather
  - libgcc
  - gxx_linux-64
  - python                          
  - pip
  - pandas-profiling
  - plotly
  - jupyterlab-plotly-extension
  - rpy2                         
  - rsa                           
  - scikit-image                  
  - scikit-learn 
  - sklearn-pandas        
  - dask
  - pandas-datareader             
  - pandas-gbq                    
  - pandocfilters 
  - tensorboard                   
  - tensorboard-plugin-wit        
  - tensorflow                    
  - tensorflow-datasets           
  - tensorflow-estimator          
  - tensorflow-hub                
  - tensorflow-metadata           
  - tensorflow-probability        
  - torchtext                     
  - torchvision                   
  - tornado   
  - Keras                         
  - Keras-Preprocessing           
  - matplotlib                    
  - matplotlib-venn
  - plotly
  - pycountry
  - scipy                         
  - scs                           
  - seaborn
  - statsmodels==0.12.1
  - nbconvert                     
  - nbformat                      
  - nest-asyncio                  
  - networkx                      
  - nibabel                       
  - nltk                          
  - notebook                      
  - numba                         
  - numexpr                       
  - numpy                         
  - oauth2client                  
  - oauthlib      
  - pytorch